# Generated by Django 2.2 on 2021-09-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0002_auto_20210922_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name=' имя')),
                ('email', models.CharField(default='', max_length=1000, verbose_name='почта')),
                ('price', models.IntegerField(default=0, verbose_name='номер')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.AdvertisementContact'),
        ),
    ]
