# Generated by Django 2.2 on 2021-09-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0004_auto_20210924_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisementrub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rub', models.CharField(default='', max_length=1000, verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements_app', to='advertisements_app.AdvertisementContact'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='rubrika',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements_app', to='advertisements_app.Advertisementrub'),
        ),
    ]
