# Generated by Django 2.2 on 2022-02-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_trans', '0003_auto_20220224_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'new', 'verbose_name_plural': 'news'},
        ),
    ]
