# Generated by Django 2.2 on 2021-12-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0004_auto_20211207_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_files.File'),
        ),
    ]
