# Generated by Django 2.2 on 2021-12-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0005_news_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_files.News'),
        ),
    ]
