# Generated by Django 2.2 on 2021-12-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0006_auto_20211217_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='teg',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
