# Generated by Django 2.2 on 2021-12-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_files', '0007_auto_20211217_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='teg',
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
