# Generated by Django 4.0.3 on 2022-04-12 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('basic', 'basic'), ('medium', 'medium'), ('premium', 'premium')], default='basic', max_length=30)),
                ('balance', models.IntegerField(default=0)),
                ('sum_buying', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
